### ISSUE TITLE
Referencing in code book.

### ISSUE THREAD

**Issue by dawkinsmw** [QuantEcon/book-networks#15]
@jstac what should referencing look like in the code book?
Should there be a bibliography, links to the articles, no links or should I avoid references?

**Comment by jstac** [comment]
Good question.  Links to articles is probably the easiest, if there's a small number.  

Otherwise you can follow other QE lectures, such as this one: https://python.quantecon.org/zreferences.html

I'll let you make the call.  Thanks @dawkinsmw .
