### ISSUE TITLE
Setup `quantecon_book_networks` as a PyPI package

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/book-networks#19]
Setup the `quantecon_book_networks` as a `PyPI` package to facilitate students building images etc.

**Comment by jstac** [comment]
Link instances of the phrase `quantecon_book_networks` to the package.  

Add `pip install ...` to the top of each lecture and check everything still runs.

**Comment by jstac** [comment]
Can this be closed @mmcky ?

**Comment by mmcky** [comment]
I have actually been working on this today. Just switching it over to a pip installable package. While I am at it I am using `flit` which `ebp` projects are switching over to use so thought it should be setup this way. 

- [ ] use `flit` packaging
- [ ] package data -- internally to the package using `pkg_resources`
- [ ] publish on `PyPI`
- [ ] update `md` files to install `pip install quantecon_book_networks`

**Comment by mmcky** [comment]
This is now packaged 

https://github.com/QuantEcon/quantecon-book-networks
