### ISSUE TITLE
Issues with homepage

### ISSUE THREAD

**Issue by jstac** [QuantEcon/book-networks#23]
Issues with https://quantecon.github.io/book-networks/intro.html

Can we get "and" between the authors instead of a comma?  Also, in the title, can we have "Theory and Computation" on a new line?

Don't worry if it's too hard.

Also, from an earlier email to @mmcky 

Would you mind to add this abstract to the networks text homepage?

This textbook is an introduction to economic networks, intended for
students and researchers in the fields of economics and applied
mathematics. The textbook emphasizes quantitative modeling, with the
main underlying tools being graph theory, linear algebra, fixed point
theory and programming. The text is suitable for a one-semester
course, taught either to advanced undergraduate students who are
comfortable with linear algebra or to beginning graduate students.

Perhaps it could go after authors.

Many thanks.

**Comment by jstac** [comment]
Also, figure for PDF is broken.

**Comment by mmcky** [comment]
@jstac did you want the abstract in a special admonition or free text as per:

<img width="837" alt="Screen Shot 2022-03-30 at 10 39 39 am" src="https://user-images.githubusercontent.com/8263752/160723613-4c679c91-3840-466c-b441-b7e7112d4705.png">

> Also, figure for PDF is broken.

not seeing this on my end. Maybe I can drop by and have a look at your machine?

> in the title, can we have "Theory and Computation" on a new line?

good question. Don't see a way to do this in markdown or rst at the moment. Will look into this. `subtitles` in both are sections really. But it would be nice to have the power to format a title. Maybe we need a `title` admonition.

**Comment by mmcky** [comment]
@jstac added a substitution to get this line break. Works for now while I find a better solution 

<img width="837" alt="Screen Shot 2022-03-30 at 10 57 21 am" src="https://user-images.githubusercontent.com/8263752/160724973-a253f534-ee12-495e-b3f0-69f210c8361e.png">
