### ISSUE TITLE
May I translate the code to Mathematica?

### ISSUE THREAD

**Issue by haihan-yu** [QuantEcon/book-networks#33]
This book is really fantastic. I would like to translate the code in this book into Wolfram Language/Mathematica and put the Jupyter notebooks in Github. Can I?

**Comment by jstac** [comment]
@haihan-yu , sorry for the slow reply.  I accidentally missed this.

Yes, a Mathematica version would be most welcome.  As long as the quality is good, we will add a link to your work and a grateful acknowledgement.  Please keep me up to date.  If necessary, you can reach me via <john.stachurski@gmail.com>

**Comment by haihan-yu** [comment]
Thanks for your permission. I will get you back when I finish it!
