### ISSUE TITLE
[add_feature] export figures

### ISSUE THREAD

**Issue by shlff** [QuantEcon/book-networks#36]
Related code:
```
export_figures = False
```
and
```
if export_figures == True:
	plt.savefig("figures/xx.pdf")
```
where ``xx`` is the figure’s name.

export_figures name lists for each chapter:

ch_intro
- [x] crude_oil_2019.pdf
- [x] commercial_aircraft_2019_1.pdf
- [x] simplex_1.pdf
- [x] heavy_tailed_draws.pdf
- [x] ccdf_comparison_1.pdf
- [x] empirical_powerlaw_plots_firms_forbes.pdf
- [x] zeta_1.pdf
- [x] networkx_basics_1.pdf
- [ ] financial_network_analysis_visualization.pdf
- [x] financial_network_analysis_centrality.pdf
- [x] commercial_aircraft_2019_2.pdf
- [x] rand_graph_experiments_1.pdf
- [x] rand_graph_experiments_2.pdf

ch_production
- [ ] input_output_analysis_15.pdf
- [x] input_output_analysis_71.pdf
- [x] input_output_analysis_15_leo.pdf
- [x] input_output_analysis_15_shocks.pdf
- [x] input_output_analysis_15_ec.pdf
- [x] input_output_analysis_aus_114.pdf
- [x] input_output_analysis_15_omult.pdf
- [ ] input_output_analysis_15_fwd.pdf
- [x] input_output_analysis_15_up.pdf
- [ ] gdp_growth.pdf
- [x] input_output_analysis_15_katz.pdf

ch_opt
- [x] shortest_path_iter_1.pdf
- [x] betweenness_centrality_1.pdf
- [x] linear_programming_1.pdf
- [x] ot_figs_1.pdf
- [x] ot_large_scale_1.pdf

ch_mcs
- [x] markov_matrix_visualization.pdf
- [x] benhabib_mobility_mixing.pdf
- [x] quah_gdppc_prediction.pdf
- [x] simplex_2.pdf
- [x] simplex_3.pdf
- [x] benhabib_mobility_dists.pdf
- [x] benhabib_ergodicity_1.pdf

ch_fpms
- [x] fin_network_sims_1.pdf

appendix
- [x] func_types_1.pdf
- [x] func_types_2.pdf
- [x] three_fixed_points.pdf
- [x] complex_number.pdf
- [x] euclidean_convergence_1.pdf
- [x] span1.pdf
- [x] func_types_3.pdf
- [x] polyhedron1.pdf
- [x] saddle_1.pdf

**Comment by shlff** [comment]
Hi @jstac the figure ``saddle_1.pdf`` in the current online website has been separated into 4 plots. 

PR #39 combines these 4 figures together again, the same as the figure used in the textbook.

**Comment by shlff** [comment]
Hi @mmcky , @jstac and I decide to generate the figures used in the network textbook directly from this repo. 

To make the figures aligned with our original ones, we need lines 6-13 in a file called [initialize.py](https://github.com/jstac/networks_text/blob/main/figures_source/initialize.py) to control the figure styles.

Do you think we should 
- incorporate the corresponding code into somewhere of the current repo or 
- push it to the new repo (https://github.com/QuantEcon/quantecon-book-networks)?

Or other options?

Looking forward to your advice.

**Comment by jstac** [comment]
@mmcky , we would appreciate your advice here.  The lines to be added require a latex installation.  Will this be a problem for the GH build?

**Comment by mmcky** [comment]
@jstac the lines are `matplotlib` configurations right?

**Comment by mmcky** [comment]
@jstac to answer your question adding `latex` is no problem. We build `pdf` now for the live sites via `GitHub actions` etc.

**Comment by jstac** [comment]
OK, thanks @mmcky .  @shlff , let's remember to check that the figures look OK after this PR is merged.

**Comment by shlff** [comment]
Thanks for your great suggestion and comment @mmcky and @jstac . 

Sure @jstac I will set up the environment using ``environment.yml`` and compile the files on my local machine before you review the PR.

**Comment by Fdu-lijiachen** [comment]
Question from 'Chapter 2 - Production -Backward linkages for 15 US sectors in 2019 '
Is hub-based eigenvector with centrality backward linkage coefficient matrix right?
backward linkage may view the sight from supply side, like i is supplier of j, so I think may be use  authority-based is better?

**Comment by jstac** [comment]
Thanks for your comment @Fdu-lijiachen .  Are you referring to the color scheme of that figure?

**Comment by Fdu-lijiachen** [comment]
> Thanks for your comment @Fdu-lijiachen . Are you referring to the color scheme of that figure?

Sorry，I mean this is a question I raised about Chapter 2, but I think I put it in the wrong place. I wonder if there is a place to discuss it with you?

**Comment by jstac** [comment]
Hi @Fdu-lijiachen 

If you click on the green button near the top that says "new issue", you can open a new issue to describe the problem.  That is our standard procedure.  Otherwise, if you prefer, you can reach me by email via john.stachurski@anu.edu.au.

Your comments will be appreciated.  It's very helpful to us if you can carefully describe the issue.
