### ISSUE TITLE
weakly chained substochastic

### ISSUE THREAD

**Issue by Dan-carey** [QuantEcon/book-networks#47]
Hi, love the textbook.

There might be a slight error in the discussion of weakly chained sub-stochastic matrices. 

Consider [[0.5 0.5],[0 0]] as a 2x2 matrix. This seems to meet the definition of sub-stochastic on p.100, but I don't think it meets the definition of weakly chained sub-stochastic matrices despite having a spectral radius of 0.5. 

As for m=2, there does not exist an i st m->i on the induced weighted digraph.

Apologies if this is my confusion.

Best wishes,
Dan

**Comment by jstac** [comment]
Hi @Dan-carey , sorry I missed your message.  (I should check the issues but if I'm slow it helps to ping me as @jstac BTW)

In my understanding, the matrix we are considering is

$$
P = \begin{pmatrix}
  0.5 & 0.5 \\
  0.0 & 0.0
\end{pmatrix}
$$

Let's call the states 1 and 2.  We need to show that, from each state $m$, there exists a state $i$ with row sum strictly less than 1 that is accessible from $m$.   

Thus, we need to show that state 2 is accessible from states 1 and 2.

Certainly state 2 is accessible from state 1.  Also, every state is accessible to itself.  Hence the conditions hold and $P$ is weakly chained sub-stochastic.

Hope that helps?

**Comment by Dan-carey** [comment]
Hi, yeah thanks that does help. I see higher up in the book accessibility is defined to include the 0-step walk. What was throwing me was footnote 7, at the bottom of page 101. This claims a P^k_{i,j}>0 for some k is equivalent to accessibility and was where I was getting my previous understanding of accessibility from. Can I now take it to mean equivalent except in the case of a row of 0s in the adjacency matrix?

Cheers,
Dan

**Comment by jstac** [comment]
Good point @Dan-carey .  It was confusing.  I slightly edited the footnote to emphasize $k \geq 0$ and $P^0$ is the identity.  Thus, $j$ accessible from $i$ is equivalent to $i=j$ (when $p^0_{ij} = 1$) or $p^k_{ij} > 0$ for some $k > 0$.

Does that help to clarify?

**Comment by Dan-carey** [comment]
Awesome, thanks!
