### ISSUE TITLE
Update figures data

### ISSUE THREAD

**Issue by jstac** [QuantEcon/book-networks#50]
Update figures in 

https://networks.quantecon.org/ch_intro.html 
https://networks.quantecon.org/ch_production.html

to latest data.

**Comment by HengchengZhang** [comment]
In progress here: https://github.com/QuantEcon/quantecon-book-networks/pull/6

**Comment by HengchengZhang** [comment]
Note to myself:
1. data updated.
2. generate the pdfs in public.

**Comment by HengchengZhang** [comment]
closed via #51 #52 #53
